version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.razorpay:checkout
    versions:
    - 1.6.5
    - 1.6.6
    - 1.6.7
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
